modLoader="javafml"
loaderVersion="[31,)"
license="All rights reserved"

issueTrackerURL="https://github.com/Thuts-Mods/ThutTech/issues"

[[mods]]
    modId="thuttech"
    version="${file.jarVersion}"
    displayName="Thut Elevators"
    authors="Thutmose"
    description='''
    Dynamical Moving elevators for Minecraft!
    '''
    
[[dependencies.thuttech]]
    modId="thutcore"
    mandatory=true
    versionRange="version_thutcore"
    ordering="AFTER"
    side="BOTH"